version: '3.8'

services:
  web:
    container_name: cv
    image: nginx:latest
    ports: []
      # - "1234:80" # HTTP
    volumes:
      - ./html:/usr/share/nginx/html:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - home_network

networks:
  home_network:
    external: true
